<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Access Token' => 'Token de Acceso',
    'Auth Key' => 'Llave',
    'Cause' => 'Causa',
    'Email' => 'Correo',
    'First Name' => 'Nombre',
    'Last Name' => 'Apellido',
    'Password' => 'Contraseña',
    'Period Begin' => 'Inicio del Periodo',
    'Period End' => 'Final del Periodo',
    'Recuperation' => 'Recuperacion',
    'Type Registry ID' => 'Identificado del Tipo de Registro',
    'User ID' => 'Identificador Usuario',
    'Username' => 'Usuario',
    'Verification Code' => 'Codigo de Verificacion',
    'type_registry' => 'Tipo de Registro',
    'About' => 'Información',
    'Are you sure you want to delete this item?' => 'Estas seguro de eliminar este item?',
    'Contact' => 'Contacto',
    'Create Registry' => 'Crear Registro',
    'Create Type Registry' => 'Crear Tipo de Registro',
    'Delete' => 'Borrar',
    'Home' => 'Inicio',
    'Login' => 'Entrar',
    'Logout' => 'Salir',
    'My Company' => 'Compañia',
    'Registries' => 'Registro',
    'Reset' => 'Reiniciar',
    'Search' => 'Buscar',
    'Type Registries' => 'Tipo de Registro',
    'Update' => 'Actualizar',
    'Update Registry: ' => 'Actualizar Registro',
    'Update Type Registry: ' => 'Actualizar Tipo de Registro',
    'confirm' => 'Confirmar',
    'description' => 'Descripcion',
    'name' => 'Nombre',
    'period_begin' => 'Periodo Inicio',
    'period_end' => 'Periodo Final',
    'period_range' => 'Rango del Periodo',
    'recuperation' => 'Recuperación',
    'Description' => 'Descripcion',
    'ID' => 'Identificador',
    'Name' => 'Nombre',
];
