<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'About' => 'Información',
    'Are you sure you want to delete this item?' => 'Estas seguro de eliminar este item?',
    'Contact' => 'Contacto',
    'Create Registry' => 'Crear Registro',
    'Delete' => 'Borrar',
    'Home' => 'Inicio',
    'Login' => 'Entrar',
    'Logout' => 'Salir',
    'My Company' => 'Compañia',
    'Registries' => 'Registro',
    'Reset' => 'Reiniciar',
    'Search' => 'Buscar',
    'Update' => 'Actualizar',
    'cause' => 'Causa',
    'confirm' => 'Confirmar',
    'create' => 'Crear',
    'id' => 'Identificador',
    'period_begin' => 'Periodo Inicio',
    'period_end' => 'Periodo Final',
    'period_range' => 'Rango del Periodo',
    'recuperation' => 'Recuperación',
    'typeRegistry.name' => 'Nombre tipo de Registro',
    'user.first_name' => 'Nombre usuario',
    'user.last_name' => 'Apellido Usuario',
];
