<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Access Token' => '',
    'Auth Key' => '',
    'Cause' => '',
    'Description' => '',
    'Email' => '',
    'First Name' => '',
    'ID' => '',
    'Last Name' => '',
    'Name' => '',
    'Password' => '',
    'Period Begin' => '',
    'Period End' => '',
    'Recuperation' => '',
    'Type Registry ID' => '',
    'User ID' => '',
    'Username' => '',
    'Verification Code' => '',
    'type_registry' => '',
    'About' => '@@@@',
    'Are you sure you want to delete this item?' => '@@@@',
    'Contact' => '@@@@',
    'Create Registry' => '@@@@',
    'Create Type Registry' => '@@@@',
    'Delete' => '@@@@',
    'Home' => '@@@@',
    'Login' => '@@@@',
    'Logout' => '@@@@',
    'My Company' => '@@@@',
    'Registries' => '@@@@',
    'Reset' => '@@@@',
    'Search' => '@@@@',
    'Type Registries' => '@@@@',
    'Update' => '@@@@',
    'Update Registry: ' => '@@@@',
    'Update Type Registry: ' => '@@@@',
    'cause' => '@@@@',
    'confirm' => '@@@@',
    'create' => '@@@@',
    'description' => '@@@@',
    'id' => '@@@@',
    'name' => '@@@@',
    'period_begin' => '@@@@',
    'period_end' => '@@@@',
    'period_range' => '@@@@',
    'recuperation' => '@@@@',
    'typeRegistry.name' => '@@@@',
    'user.first_name' => '@@@@',
    'user.last_name' => '@@@@',
];
